CREATE TABLE IF NOT EXISTS urls (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS url_checks (
    id SERIAL PRIMARY KEY,
    url_id INTEGER REFERENCES urls(id),
    code INTEGER,
    h1 TEXT,
    title TEXT,
    description TEXT,
    checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);